//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace arduino.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.webserver_arduinoSoap")]
    public interface webserver_arduinoSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  webserver_arduino_controlResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webserver_arduino_control", ReplyAction="*")]
        arduino.ServiceReference1.webserver_arduino_controlResponse webserver_arduino_control(arduino.ServiceReference1.webserver_arduino_controlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webserver_arduino_control", ReplyAction="*")]
        System.Threading.Tasks.Task<arduino.ServiceReference1.webserver_arduino_controlResponse> webserver_arduino_controlAsync(arduino.ServiceReference1.webserver_arduino_controlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webserver_arduino_controlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webserver_arduino_control", Namespace="http://tempuri.org/", Order=0)]
        public arduino.ServiceReference1.webserver_arduino_controlRequestBody Body;
        
        public webserver_arduino_controlRequest() {
        }
        
        public webserver_arduino_controlRequest(arduino.ServiceReference1.webserver_arduino_controlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class webserver_arduino_controlRequestBody {
        
        public webserver_arduino_controlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webserver_arduino_controlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webserver_arduino_controlResponse", Namespace="http://tempuri.org/", Order=0)]
        public arduino.ServiceReference1.webserver_arduino_controlResponseBody Body;
        
        public webserver_arduino_controlResponse() {
        }
        
        public webserver_arduino_controlResponse(arduino.ServiceReference1.webserver_arduino_controlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webserver_arduino_controlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string webserver_arduino_controlResult;
        
        public webserver_arduino_controlResponseBody() {
        }
        
        public webserver_arduino_controlResponseBody(string webserver_arduino_controlResult) {
            this.webserver_arduino_controlResult = webserver_arduino_controlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webserver_arduinoSoapChannel : arduino.ServiceReference1.webserver_arduinoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webserver_arduinoSoapClient : System.ServiceModel.ClientBase<arduino.ServiceReference1.webserver_arduinoSoap>, arduino.ServiceReference1.webserver_arduinoSoap {
        
        public webserver_arduinoSoapClient() {
        }
        
        public webserver_arduinoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webserver_arduinoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webserver_arduinoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webserver_arduinoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        arduino.ServiceReference1.webserver_arduino_controlResponse arduino.ServiceReference1.webserver_arduinoSoap.webserver_arduino_control(arduino.ServiceReference1.webserver_arduino_controlRequest request) {
            return base.Channel.webserver_arduino_control(request);
        }
        
        public string webserver_arduino_control() {
            arduino.ServiceReference1.webserver_arduino_controlRequest inValue = new arduino.ServiceReference1.webserver_arduino_controlRequest();
            inValue.Body = new arduino.ServiceReference1.webserver_arduino_controlRequestBody();
            arduino.ServiceReference1.webserver_arduino_controlResponse retVal = ((arduino.ServiceReference1.webserver_arduinoSoap)(this)).webserver_arduino_control(inValue);
            return retVal.Body.webserver_arduino_controlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<arduino.ServiceReference1.webserver_arduino_controlResponse> arduino.ServiceReference1.webserver_arduinoSoap.webserver_arduino_controlAsync(arduino.ServiceReference1.webserver_arduino_controlRequest request) {
            return base.Channel.webserver_arduino_controlAsync(request);
        }
        
        public System.Threading.Tasks.Task<arduino.ServiceReference1.webserver_arduino_controlResponse> webserver_arduino_controlAsync() {
            arduino.ServiceReference1.webserver_arduino_controlRequest inValue = new arduino.ServiceReference1.webserver_arduino_controlRequest();
            inValue.Body = new arduino.ServiceReference1.webserver_arduino_controlRequestBody();
            return ((arduino.ServiceReference1.webserver_arduinoSoap)(this)).webserver_arduino_controlAsync(inValue);
        }
    }
}
